# Generated by Django 2.1.1 on 2018-09-10 11:54

from django.db import migrations


def create_default_application(apps, schema_editor):
    Application = apps.get_model("oauth2_provider", "Application")

    Application.objects.create(
        client_type="public",
        authorization_grant_type="authorization-code",
        skip_authorization=True,
        name="DASH-IT Frontend",
        client_secret="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("oauth2_provider", "0006_auto_20171214_2232"),
    ]

    operations = [migrations.RunPython(create_default_application)]
