# Generated by Django 2.1.1 on 2018-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_user_role")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Teacher"),
                    ("qdt", "Quality & Design Team"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        )
    ]
