# Generated by Django 2.1.1 on 2018-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30, unique=True)),
                ('course_slug', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
    ]
