# Generated by Django 2.1.1 on 2018-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_slug",
            field=models.CharField(max_length=100),
        )
    ]
