# Generated by Django 2.1.1 on 2018-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0001_initial")]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                DROP VIEW IF EXISTS course_membership_view
                """,
                """
                CREATE OR REPLACE VIEW course_memberships_view
                AS
                SELECT
                MD5(MD5(MD5(eitdigital_user_id) || course_id) || course_membership_ts) as id,
                eitdigital_user_id,
                course_id,
                course_membership_role,
                course_membership_ts
                FROM
                course_memberships;
                """,
            ],
            reverse_sql="""
            DROP VIEW course_memberships_view
            """,
        )
    ]
