# Generated by Django 2.1.1 on 2018-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0001_initial")]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW course_memberships_view
            AS
            SELECT
            MD5(MD5(course_memberships.eitdigital_user_id) || course_memberships.course_id) as id,
            course_memberships.eitdigital_user_id,
            course_memberships.course_id,
            course_memberships.course_membership_role,
            course_memberships.course_membership_ts
            FROM
            course_memberships;
            """,
            reverse_sql="""
            DROP VIEW course_memberships_view
            """,
        )
    ]
