# Generated by Django 2.1.1 on 2018-09-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0002_create_course_membership_view")]

    operations = [
        migrations.RunSQL(
            sql=[
                """DROP VIEW IF EXISTS course_branch_modules_view""",
                """
                CREATE OR REPLACE VIEW course_branch_modules_view
                AS
                SELECT
                MD5(MD5(course_branch_id) || course_module_id) as id,
                course_branch_id,
                course_module_id,
                course_branch_module_order,
                course_branch_module_name,
                course_branch_module_desc
                FROM
                course_branch_modules;
                """,
            ],
            reverse_sql="""
            DROP VIEW course_branch_modules_view
            """,
        )
    ]
