# Generated by Django 2.1.1 on 2018-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0005_create_lessons_items_view")]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE MATERIALIZED VIEW
                    course_progress_view
                AS
                SELECT
                    MD5(MD5(MD5(MD5(MD5(MD5(course_id) || course_branch_id) || course_item_id) || eitdigital_user_id) || course_progress_state_type_id) || course_progress_ts)::varchar(50) as id,
                    course_id,
                    MD5(MD5(course_branch_id) || course_item_id)::varchar(50) as item_id,
                    eitdigital_user_id,
                    course_progress_state_type_id,
                    course_progress_ts
                FROM
                    course_progress
                    JOIN course_branches USING (course_id)
                    JOIN course_branch_modules USING (course_branch_id)
                    JOIN course_branch_lessons USING (course_branch_id, course_module_id)
                    JOIN course_branch_items USING (course_branch_id, course_lesson_id, course_item_id)
                """,
                """
                CREATE UNIQUE INDEX ON course_progress_view (id)
                """,
                """
                CREATE INDEX ON course_progress_view (course_id)
                """,
                """
                CREATE INDEX ON course_progress_view (item_id)
                """,
                """
                CREATE INDEX ON course_progress_view (eitdigital_user_id)
                """,
            ],
            reverse_sql="""
            DROP MATERIALIZED VIEW IF EXISTS course_progress_view
            """,
        )
    ]
