# Generated by Django 2.1.1 on 2018-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0005_create_lessons_items_view")]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE MATERIALIZED VIEW
                    course_progress_view
                AS
                SELECT
                    MD5(MD5(MD5(MD5(MD5(course_id) || course_item_id) || eitdigital_user_id) || course_progress_state_type_id) || course_progress_ts)::varchar(50) as id,
                    course_id,
                    (
                        SELECT DISTINCT ON (course_id)
                            item_id
                        FROM
                            course_branch_items_view
                            JOIN course_branch_lessons_view USING (course_branch_id, lesson_id)
                            JOIN course_branch_modules_view USING (course_branch_id, module_id)
                            JOIN course_branches USING (course_branch_id)
                        WHERE
                            course_id = course_progress.course_id
                            AND course_item_id = course_progress.course_item_id
                        ORDER BY course_id, authoring_course_branch_created_ts DESC NULLS LAST
                    )::varchar(50) as item_id,
                    eitdigital_user_id,
                    course_progress_state_type_id,
                    course_progress_ts
                FROM
                    course_progress
                """,
                """
                CREATE UNIQUE INDEX ON course_progress_view (id)
                """,
                """
                CREATE INDEX ON course_progress_view (course_id)
                """,
                """
                CREATE INDEX ON course_progress_view (item_id)
                """,
                """
                CREATE INDEX ON course_progress_view (eitdigital_user_id)
                """,
            ],
            reverse_sql="""
            DROP MATERIALIZED VIEW IF EXISTS course_progress_view
            """,
        )
    ]
