# Generated by Django 2.1.1 on 2018-09-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0007_create_item_assessment_view")]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                DROP VIEW IF EXISTS course_branch_item_programming_assignments_view
                """,
                """
                CREATE OR REPLACE VIEW course_branch_item_programming_assignments_view
                AS
                SELECT
                MD5(MD5(course_item_id) || programming_assignment_id) as id,
                course_branch_id,
                course_item_id,
                programming_assignment_id
                FROM
                course_branch_item_programming_assignments;
                """,
            ],
            reverse_sql="""
            DROP VIEW course_branch_item_programming_assignments_view
            """,
        )
    ]
