# Generated by Django 2.1.1 on 2018-10-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0013_clickstreamevent_lastactivity_lastactivitypermodule'),
        ('coursera', '0013_create_module_activity_views'),
    ]

    operations = [
    ]
