# Generated by Django 2.1.2 on 2018-10-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0020_create_response_options_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    discussion_questions_view
                AS
                SELECT
                    discussion_question_id,
                    eitdigital_user_id,
                    discussion_question_title,
                    discussion_question_details,
                    discussion_question_context_type,
                    course_id,
                    MD5(MD5(course_branch_id) || course_module_id)::varchar(50) as module_id,
                    MD5(MD5(course_branch_id) || (
                        SELECT course_item_id
                        FROM course_branch_items bi
                        WHERE bi.course_branch_id = course_branches.course_branch_id
                        AND bi.course_item_id = discussion_questions.course_item_id
                    ))::varchar(50) as item_id,
                    discussion_forum_id,
                    country_cd,
                    group_id,
                    discussion_question_created_ts,
                    discussion_question_updated_ts
                FROM
                    discussion_questions
                    JOIN course_branches USING (course_id)
                    LEFT JOIN course_branch_modules USING (course_branch_id, course_module_id)
                WHERE
                    course_branch_id = (
                        SELECT course_branch_id
                        FROM course_branches cb
                        WHERE course_branches.course_id = cb.course_id
                        ORDER BY authoring_course_branch_created_ts DESC NULLS LAST LIMIT 1
                    )
                """,
                """
                CREATE UNIQUE INDEX ON discussion_questions_view (discussion_question_id)
                """,
                """
                CREATE INDEX ON discussion_questions_view (eitdigital_user_id)
                """,
                """
                CREATE INDEX ON discussion_questions_view (course_id)
                """,
                """
                CREATE INDEX ON discussion_questions_view (module_id)
                """,
                """
                CREATE INDEX ON discussion_questions_view (item_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS discussion_questions_view",
        )
    ]
