# Generated by Django 2.1.2 on 2018-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0023_create_last_attempt_view")]

    operations = [
        migrations.RunSQL(
            # Select each unique tuple of assessment, user and date from the
            # assessment_response_actions_view.
            #
            # This view is used to calculate the average number of attempts
            # and the distribution of the number of attempts.
            #
            # quiz-analytics/
            # - average_attempts
            # - number_of_attempts
            [
                """
                DROP MATERIALIZED VIEW IF EXISTS assessment_attempts_view
                """,
                """
                CREATE MATERIALIZED VIEW
                    assessment_attempts_view
                AS
                SELECT DISTINCT
                    MD5(MD5(MD5(assessment_id) || eitdigital_user_id) || assessment_action_ts::date)::varchar(50) as id,
                    assessment_id,
                    eitdigital_user_id,
                    assessment_action_ts::date as timestamp
                FROM
                    assessment_response_actions_view
                """,
                """
                CREATE UNIQUE INDEX ON assessment_attempts_view (id)
                """,
                """
                CREATE INDEX ON assessment_attempts_view (assessment_id)
                """,
                """
                CREATE INDEX ON assessment_attempts_view (eitdigital_user_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS assessment_attempts_view",
        )
    ]
