# Generated by Django 2.1.2 on 2018-10-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0025_create_course_duration_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                DROP INDEX IF EXISTS course_progress_view_course_id_idx
                """,
                """
                CREATE INDEX ON course_progress_view (course_id, course_progress_ts)
                """,
            ],
            reverse_sql=[
                """
                DROP INDEX IF EXISTS course_progress_view_course_id_course_progress_ts_idx
                """,
                """
                CREATE INDEX ON course_progress_view (course_id)
                """,
            ],
        )
    ]
