from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0027_auto_20181015_1210")]

    operations = [
        migrations.RunSQL(
            [
                """
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Afghanistan','AF','AFG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Aland Islands','AX','ALA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Albania','AL','ALB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Algeria','DZ','DZA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('American Samoa','AS','ASM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Andorra','AD','AND');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Angola','AO','AGO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Anguilla','AI','AIA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Antarctica','AQ','ATA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Antigua and Barbuda','AG','ATG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Argentina','AR','ARG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Armenia','AM','ARM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Aruba','AW','ABW');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Australia','AU','AUS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Austria','AT','AUT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Azerbaijan','AZ','AZE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bahamas','BS','BHS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bahrain','BH','BHR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bangladesh','BD','BGD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Barbados','BB','BRB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Belarus','BY','BLR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Belgium','BE','BEL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Belize','BZ','BLZ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Benin','BJ','BEN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bermuda','BM','BMU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bhutan','BT','BTN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bolivia','BO','BOL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bosnia and Herzegovina','BA','BIH');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Botswana','BW','BWA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bouvet Island','BV','BVT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Brazil','BR','BRA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('British Virgin Islands','VG','VGB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('British Indian Ocean Territory','IO','IOT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Brunei Darussalam','BN','BRN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Bulgaria','BG','BGR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Burkina Faso','BF','BFA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Burundi','BI','BDI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cambodia','KH','KHM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cameroon','CM','CMR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Canada','CA','CAN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cape Verde','CV','CPV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cayman Islands','KY','CYM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Central African Republic','CF','CAF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Chad','TD','TCD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Chile','CL','CHL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('China','CN','CHN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Hong Kong, SAR China','HK','HKG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Macao, SAR China','MO','MAC');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Christmas Island','CX','CXR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cocos (Keeling) Islands','CC','CCK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Colombia','CO','COL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Comoros','KM','COM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Congo (Brazzaville)','CG','COG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Congo, (Kinshasa)','CD','COD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cook Islands','CK','COK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Costa Rica','CR','CRI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Côte d''Ivoire','CI','CIV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Croatia','HR','HRV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cuba','CU','CUB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Cyprus','CY','CYP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Czech Republic','CZ','CZE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Denmark','DK','DNK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Djibouti','DJ','DJI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Dominica','DM','DMA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Dominican Republic','DO','DOM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Ecuador','EC','ECU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Egypt','EG','EGY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('El Salvador','SV','SLV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Equatorial Guinea','GQ','GNQ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Eritrea','ER','ERI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Estonia','EE','EST');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Ethiopia','ET','ETH');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Falkland Islands (Malvinas)','FK','FLK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Faroe Islands','FO','FRO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Fiji','FJ','FJI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Finland','FI','FIN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('France','FR','FRA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('French Guiana','GF','GUF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('French Polynesia','PF','PYF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('French Southern Territories','TF','ATF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Gabon','GA','GAB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Gambia','GM','GMB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Georgia','GE','GEO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Germany','DE','DEU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Ghana','GH','GHA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Gibraltar','GI','GIB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Greece','GR','GRC');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Greenland','GL','GRL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Grenada','GD','GRD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guadeloupe','GP','GLP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guam','GU','GUM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guatemala','GT','GTM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guernsey','GG','GGY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guinea','GN','GIN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guinea-Bissau','GW','GNB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Guyana','GY','GUY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Haiti','HT','HTI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Heard and Mcdonald Islands','HM','HMD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Holy See (Vatican City State)','VA','VAT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Honduras','HN','HND');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Hungary','HU','HUN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Iceland','IS','ISL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('India','IN','IND');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Indonesia','ID','IDN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Iran, Islamic Republic of','IR','IRN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Iraq','IQ','IRQ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Ireland','IE','IRL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Isle of Man','IM','IMN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Israel','IL','ISR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Italy','IT','ITA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Jamaica','JM','JAM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Japan','JP','JPN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Jersey','JE','JEY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Jordan','JO','JOR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Kazakhstan','KZ','KAZ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Kenya','KE','KEN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Kiribati','KI','KIR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Korea (North)','KP','PRK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Korea (South)','KR','KOR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Kuwait','KW','KWT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Kyrgyzstan','KG','KGZ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Lao PDR','LA','LAO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Latvia','LV','LVA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Lebanon','LB','LBN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Lesotho','LS','LSO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Liberia','LR','LBR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Libya','LY','LBY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Liechtenstein','LI','LIE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Lithuania','LT','LTU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Luxembourg','LU','LUX');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Macedonia, Republic of','MK','MKD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Madagascar','MG','MDG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Malawi','MW','MWI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Malaysia','MY','MYS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Maldives','MV','MDV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mali','ML','MLI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Malta','MT','MLT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Marshall Islands','MH','MHL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Martinique','MQ','MTQ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mauritania','MR','MRT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mauritius','MU','MUS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mayotte','YT','MYT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mexico','MX','MEX');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Micronesia, Federated States of','FM','FSM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Moldova','MD','MDA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Monaco','MC','MCO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mongolia','MN','MNG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Montenegro','ME','MNE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Montserrat','MS','MSR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Morocco','MA','MAR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Mozambique','MZ','MOZ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Myanmar','MM','MMR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Namibia','NA','NAM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Nauru','NR','NRU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Nepal','NP','NPL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Netherlands','NL','NLD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Netherlands Antilles','AN','ANT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('New Caledonia','NC','NCL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('New Zealand','NZ','NZL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Nicaragua','NI','NIC');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Niger','NE','NER');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Nigeria','NG','NGA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Niue','NU','NIU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Norfolk Island','NF','NFK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Northern Mariana Islands','MP','MNP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Norway','NO','NOR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Oman','OM','OMN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Pakistan','PK','PAK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Palau','PW','PLW');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Palestinian Territory','PS','PSE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Panama','PA','PAN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Papua New Guinea','PG','PNG');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Paraguay','PY','PRY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Peru','PE','PER');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Philippines','PH','PHL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Pitcairn','PN','PCN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Poland','PL','POL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Portugal','PT','PRT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Puerto Rico','PR','PRI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Qatar','QA','QAT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Réunion','RE','REU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Romania','RO','ROU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Russian Federation','RU','RUS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Rwanda','RW','RWA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint-Barthélemy','BL','BLM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint Helena','SH','SHN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint Kitts and Nevis','KN','KNA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint Lucia','LC','LCA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint-Martin (French part)','MF','MAF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint Pierre and Miquelon','PM','SPM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saint Vincent and Grenadines','VC','VCT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Samoa','WS','WSM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('San Marino','SM','SMR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Sao Tome and Principe','ST','STP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Saudi Arabia','SA','SAU');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Senegal','SN','SEN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Serbia','RS','SRB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Seychelles','SC','SYC');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Sierra Leone','SL','SLE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Singapore','SG','SGP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Slovakia','SK','SVK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Slovenia','SI','SVN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Solomon Islands','SB','SLB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Somalia','SO','SOM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('South Africa','ZA','ZAF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('South Georgia and the South Sandwich Islands','GS','SGS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('South Sudan','SS','SSD');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Spain','ES','ESP');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Sri Lanka','LK','LKA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Sudan','SD','SDN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Suriname','SR','SUR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Svalbard and Jan Mayen Islands','SJ','SJM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Swaziland','SZ','SWZ');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Sweden','SE','SWE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Switzerland','CH','CHE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Syrian Arab Republic (Syria)','SY','SYR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Taiwan, Republic of China','TW','TWN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tajikistan','TJ','TJK');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tanzania, United Republic of','TZ','TZA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Thailand','TH','THA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Timor-Leste','TL','TLS');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Togo','TG','TGO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tokelau','TK','TKL');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tonga','TO','TON');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Trinidad and Tobago','TT','TTO');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tunisia','TN','TUN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Turkey','TR','TUR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Turkmenistan','TM','TKM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Turks and Caicos Islands','TC','TCA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Tuvalu','TV','TUV');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Uganda','UG','UGA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Ukraine','UA','UKR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('United Arab Emirates','AE','ARE');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('United Kingdom','GB','GBR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('United States of America','US','USA');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('US Minor Outlying Islands','UM','UMI');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Uruguay','UY','URY');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Uzbekistan','UZ','UZB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Vanuatu','VU','VUT');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Venezuela (Bolivarian Republic)','VE','VEN');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Viet Nam','VN','VNM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Virgin Islands, US','VI','VIR');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Wallis and Futuna Islands','WF','WLF');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Western Sahara','EH','ESH');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Yemen','YE','YEM');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Zambia','ZM','ZMB');
                INSERT INTO country2to3("country","two_let","three_let") VALUES ('Zimbabwe','ZW','ZWE');
                """
            ],
            reverse_sql=[
                """
                    DROP TABLE country2to3;
                """
            ],
        )
    ]
