# Generated by Django 2.1.2 on 2018-10-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0028_country2to3")]

    operations = [
        migrations.RunSQL(
            # For each assessment, select the unique tuples of question and
            # date. For each tuple, calculate the total number of selected
            # and correct answers up to that date.
            #
            # This view is used to calculate the correctness ratio of each
            # question. The total number of selected and correct answers is
            # precalculated for each date using a window expression for
            # performance reasons.
            #
            # The count for a specific timespan can be calculated by
            # subtracting the count at the start of that timespan from the
            # count at the end of that timespan.
            #
            # quiz-analytics/
            # - correct_ratio_per_question
            [
                """
                CREATE MATERIALIZED VIEW
                    assessment_answers_over_time_view
                AS
                SELECT DISTINCT ON (assessment_id, assessment_question_id, assessment_action_ts::date)
                    MD5(MD5(MD5(assessment_id) || assessment_question_id) || assessment_action_ts::date)::varchar(50) as id,
                    assessment_id,
                    assessment_question_id,
                    assessment_action_ts::date,
                    COUNT(assessment_option_id)
                        FILTER (WHERE assessment_response_selected = True)
                        OVER (PARTITION BY assessment_id, assessment_question_id, assessment_action_ts::date ORDER BY assessment_action_ts::date) AS count_selected,
                    COUNT(assessment_option_id)
                        FILTER (WHERE assessment_response_selected = True AND assessment_response_correct = True)
                        OVER (PARTITION BY assessment_id, assessment_question_id, assessment_action_ts::date ORDER BY assessment_action_ts::date) as count_correct
                    FROM
                        assessment_response_actions_view
                        LEFT OUTER JOIN assessment_response_options_view USING (assessment_response_id)
                    ORDER BY
                        assessment_id,
                        assessment_question_id,
                        assessment_action_ts::date
                """,
                """
                CREATE UNIQUE INDEX ON assessment_answers_over_time_view (id)
                """,
                """
                CREATE INDEX ON assessment_answers_over_time_view (assessment_id)
                """,
                """
                CREATE INDEX ON assessment_answers_over_time_view (assessment_action_ts)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS assessment_answers_over_time_view",
        )
    ]
