# Generated by Django 2.1.2 on 2018-10-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0029_create_answers_over_time_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    peer_assignments_view
                AS
                SELECT
                    peer_assignment_id,
                    peer_assignment_base_id,
                    peer_assignment_type,
                    peer_assignment_required_review_count,
                    peer_assignment_passing_fraction,
                    peer_assignment_required_reviewer_count_for_score,
                    peer_assignment_required_wait_for_score_ms,
                    peer_assignment_maximum_score,
                    peer_assignment_update_ts,
                    peer_assignment_is_mentor_graded
                FROM
                    peer_assignments
                """,
                """
                CREATE UNIQUE INDEX ON peer_assignments_view (peer_assignment_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS peer_assignments_view",
        ),
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    peer_submissions_view
                AS
                SELECT
                    peer_submission_id,
                    peer_assignment_id,
                    eitdigital_user_id,
                    peer_submission_created_ts,
                    peer_submission_is_draft,
                    peer_submission_title,
                    peer_submission_removed_from_public_ts,
                    peer_submission_score_available_ts,
                    peer_submission_score,
                    peer_submission_is_mentor_graded
                FROM
                    peer_submissions
                """,
                """
                CREATE UNIQUE INDEX ON peer_submissions_view (peer_submission_id)
                """,
                """
                CREATE INDEX ON peer_submissions_view (peer_assignment_id)
                """,
                """
                CREATE INDEX ON peer_submissions_view (eitdigital_user_id)
                """,
                """
                CREATE INDEX ON peer_submissions_view (peer_submission_created_ts)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS peer_submissions_view",
        ),
    ]
