# Generated by Django 2.1.2 on 2018-10-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0030_peer_assignment_views")]

    operations = [
        migrations.RunSQL(
            """ALTER MATERIALIZED VIEW heartbeat_events RENAME TO heartbeat_events_view""",
            reverse_sql="""ALTER MATERIALIZED VIEW heartbeat_events_view RENAME TO heartbeat_events""",
        ),
        migrations.RunSQL(
            """ALTER MATERIALIZED VIEW last_activity_per_module RENAME TO last_activity_per_module_view""",
            reverse_sql="""ALTER MATERIALIZED VIEW last_activity_per_module_view RENAME TO last_activity_per_module""",
        ),
    ]
