# Generated by Django 2.1.2 on 2018-10-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0031_rename_views")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    course_item_types_view
                AS
                SELECT
                    course_item_type_id,
                    course_item_type_desc,
                    course_item_type_category,
                    course_item_type_graded,
                    atom_content_type_id
                FROM
                    course_item_types
                """,
                """
                CREATE UNIQUE INDEX ON course_item_types_view (course_item_type_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS course_item_types_view",
        )
    ]
