# Generated by Django 2.1.2 on 2018-10-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0032_create_course_item_types_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    on_demand_sessions_view
                AS
                SELECT
                    course_id,
                    on_demand_session_id,
                    on_demand_sessions_start_ts,
                    on_demand_sessions_end_ts,
                    on_demand_sessions_enrollment_end_ts,
                    course_branch_id
                FROM
                    on_demand_sessions
                """,
                """
                CREATE UNIQUE INDEX ON on_demand_sessions_view (on_demand_session_id)
                """,
                """
                CREATE INDEX ON on_demand_sessions_view (course_id)
                """,
                """
                CREATE INDEX ON on_demand_sessions_view (course_branch_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS on_demand_sessions_view",
        )
    ]
