# Generated by Django 2.1.2 on 2018-10-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0034_create_users_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    courses_view
                AS
                SELECT
                    course_id,
                    course_slug,
                    course_name,
                    course_launch_ts,
                    course_update_ts,
                    course_deleted,
                    course_graded,
                    course_desc,
                    course_restricted,
                    course_verification_enabled_at_ts,
                    primary_translation_equivalent_course_id,
                    course_preenrollment_ts,
                    course_workload,
                    course_session_enabled_ts,
                    course_promo_photo_s3_bucket,
                    course_promo_photo_s3_key,
                    course_level,
                    course_planned_launch_date_text,
                    course_header_image_s3_bucket,
                    course_header_image_s3_key
                FROM
                    courses
                """,
                """
                CREATE UNIQUE INDEX ON courses_view (course_id)
                """,
                """
                CREATE INDEX ON courses_view (course_slug)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS courses_view",
        )
    ]
