# Generated by Django 2.1.2 on 2018-10-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0035_create_courses_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE MATERIALIZED VIEW
                    course_branches_view
                AS
                SELECT
                    course_id,
                    course_branch_id,
                    course_branch_changes_description,
                    authoring_course_branch_name,
                    authoring_course_branch_created_ts
                FROM
                    course_branches
                """,
                """
                CREATE UNIQUE INDEX ON course_branches_view (course_branch_id)
                """,
                """
                CREATE INDEX ON course_branches_view (course_id)
                """,
            ],
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS course_branches_view",
        )
    ]
