# Generated by Django 2.1.2 on 2018-10-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0036_create_course_branches_view")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE INDEX ON assessment_attempts_view (assessment_id, eitdigital_user_id)
                """,
                """
                CREATE INDEX ON clickstream_events_view (course_id, key, server_timestamp)
                """,
            ],
            reverse_sql="",
        )
    ]
