# Generated by Django 2.1.2 on 2018-10-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0037_create_indexes")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE INDEX ON heartbeat_events_view (item_id, server_timestamp)
                """,
                """
                DROP INDEX IF EXISTS heartbeat_events_view_item_id_idx
                """,
            ],
            reverse_sql="",
        )
    ]
