# Generated by Django 2.1.2 on 2018-10-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0041_create_module_duration_view")]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX ON clickstream_events_view (course_id, key, ((value)::jsonb -> 'item_id'), server_timestamp)
            """,
            reverse_sql="",
        )
    ]
