# Generated by Django 2.1.2 on 2018-10-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursera", "0042_create_clickstream_index")]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE INDEX ON course_progress_view (item_id, course_progress_ts, eitdigital_user_id)
                """,
                """
                CREATE INDEX ON course_item_grades_view (item_id, course_item_grade_ts, course_item_grade_overall)
                """,
                """
                CREATE INDEX ON course_branch_item_peer_assignments_view (item_id, peer_assignment_id)
                """,
                """
                CREATE INDEX ON peer_submissions_view (peer_assignment_id, peer_submission_created_ts, eitdigital_user_id)
                """,
                """
                CREATE INDEX ON assessment_last_attempt_view (assessment_id, assessment_action_ts, score, id)
                """,
                """
                CREATE INDEX ON assessment_attempts_view (assessment_id, eitdigital_user_id, timestamp)
                """,
                """
                CREATE INDEX ON module_duration_view (module_id, module_start_ts, duration)
                """,
                """
                CREATE INDEX ON last_activity_per_module_view (module_id, course_progress_ts)
                """,
                """
                CREATE INDEX ON assessment_answers_over_time_view (assessment_id, assessment_question_id, count_selected, count_correct)
                """,
                """
                CREATE INDEX ON heartbeat_events_view (item_id, timecode)
                """,
                """
                CREATE INDEX ON course_item_grades_view (item_id, course_item_passing_state_desc, id)
                """,
                """
                CREATE INDEX ON course_memberships_view (course_id, course_membership_role, course_membership_ts, eitdigital_user_id)
                """,
                """
                CREATE INDEX ON course_grades_view (course_id, course_passing_state_desc, course_grade_ts)
                """,
                """
                CREATE INDEX ON course_duration_view (course_id, course_progress_start_ts, duration)
                """,
                """
                CREATE INDEX ON feedback_course_ratings_view (course_id, feedback_system, feedback_ts, feedback_rating, id)
                """,
                """
                CREATE INDEX ON course_grades_view (course_id, course_passing_state_desc, course_grade_ts, eitdigital_user_id)
                """,
            ],
            reverse_sql="",
        )
    ]
